---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: shestera/scaletestapp
          imagePullPolicy: Always
          ports:
            - name: backend
              containerPort: 8080
          resources:
            requests:
              memory: "5Mi"
              cpu: "100m"
            limits:
              memory: "30Mi"
              cpu: "200m"
