---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-sm
  namespace: default
  labels:
    release: prometheus-operator
spec:
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: backend
      prometheus-monitored: "true"