http {
  limit_req_zone $binary_remote_addr zone=perip:10m rate=10r/s;
  upstream backend_servers {
      server backend1.example.com;
      server backend2.example.com;
      server backend3.example.com;
  }

  server {
      listen 80;
  
      limit_req zone=perip burst=10;
      limit_req_status 429;

      location / {
          proxy_pass http://backend_servers;
      }

  }
}
 